# vim ft=yaml
# CI on Windows via appveyor

environment:
  global:
    REPO_DIR: metric
    PACKAGE_DIR: metric/python
    PACKAGE_NAME: metric-py
    BUILD_COMMIT: master
    NP_BUILD_DEP: "auditwheel==3.1.0"
    NP_TEST_DEP: "pytest"
    BOOST_ROOT: "C:/Libraries/boost_1_71_0"
    GNOME_BASE_URL: "http://ftp.gnome.org/pub/gnome/binaries/win32"
    BLAS_LIBRARIES: "C:/opt/lib"
    MKL_THREADING_LAYER: GNU
    PKG_CONFIG: "C:/pkg-config/bin/pkg-config.exe"
    CMAKE_GENERATOR: "Visual Studio 16 2019"
    MKL_URL: "https://github-production-release-asset-2e65be.s3.amazonaws.com/249880034/6b1f7200-76e6-11ea-82ad-37c3e0edfb8f?X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Credential=AKIAIWNJYAX4CSVEH53A%2F20200405%2Fus-east-1%2Fs3%2Faws4_request&X-Amz-Date=20200405T064647Z&X-Amz-Expires=300&X-Amz-Signature=0ebfff7f71596f3950772e0eb0b6922c684e47c7cc95074402c412a0b9a87549&X-Amz-SignedHeaders=host&actor_id=0&response-content-disposition=attachment%3B%20filename%3Dw_mkl_2020.1.216.exe.zip&response-content-type=application%2Foctet-stream"

  matrix:
#    - PYTHON: C:\Python36
#      CMAKE_GENERATOR_PLATFORM: Win32
    - PYTHON: C:\Python36-x64
      CMAKE_GENERATOR_PLATFORM: x64
    - PYTHON: C:\Python37
      CMAKE_GENERATOR_PLATFORM: Win32
    - PYTHON: C:\Python37-x64
      CMAKE_GENERATOR_PLATFORM: x64
    - PYTHON: C:\Python38
      CMAKE_GENERATOR_PLATFORM: Win32
    - PYTHON: C:\Python38-x64
      CMAKE_GENERATOR_PLATFORM: x64

matrix:
    fast_finish: true

install:
  # Fetch submodules
  - git submodule update --init --recursive
#  - if %platform% == "x64" SET PYTHON="%PYTHON%-%platform%"
  # Install new Python if necessary
  - ps: .\multibuild\install_python.ps1

  # Prepend newly installed Python to the PATH of this build (this cannot be
  # done from inside the powershell script as it would require to restart
  # the parent CMD process).
  - SET PATH=%PYTHON%;%PYTHON%\Scripts;%PATH%
  - python -m pip install -U pip setuptools wheel urllib3

  # Fix MSVC builds for 64-bit Python. See:
  # http://stackoverflow.com/questions/32091593/cannot-install-windows-sdk-7-1-on-windows-10
  - echo "C:\Program Files\Microsoft SDKs\Windows\v7.1\Bin\SetEnv.cmd" /x64 > "C:\Program Files (x86)\Microsoft Visual Studio 10.0\VC\bin\amd64/vcvars64.bat"

  # Check that we have the expected version and architecture for Python
  - python --version
  - python -c "import struct; print(struct.calcsize('P') * 8)"

  # Install OpenBLAS
  - ps: |
      $PYTHON = $env:PYTHON
      $lib = python ./openblas_support.py
      md $env:BLAS_LIBRARIES
      $destination = "$env:BLAS_LIBRARIES/openblas.lib"
      cp $lib $destination
      ls $destination

  #- python -m pip install mkl
  - curl -LO https://github-production-release-asset-2e65be.s3.amazonaws.com/249880034/6b1f7200-76e6-11ea-82ad-37c3e0edfb8f?X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Credential=AKIAIWNJYAX4CSVEH53A%2F20200405%2Fus-east-1%2Fs3%2Faws4_request&X-Amz-Date=20200405T064647Z&X-Amz-Expires=300&X-Amz-Signature=0ebfff7f71596f3950772e0eb0b6922c684e47c7cc95074402c412a0b9a87549&X-Amz-SignedHeaders=host&actor_id=0&response-content-disposition=attachment%3B%20filename%3Dw_mkl_2020.1.216.exe.zip&response-content-type=application%2Foctet-stream
  - 7z x -y w_mkl_2020.1.216.exe.zip -oC:\MKL\

  # Install PkgConfig
  - curl -LO %GNOME_BASE_URL%/dependencies/pkg-config_0.26-1_win32.zip
  - curl -LO %GNOME_BASE_URL%/glib/2.28/glib_2.28.8-1_win32.zip
  - curl -LO %GNOME_BASE_URL%/dependencies/gettext-runtime_0.18.1.1-2_win32.zip
  - 7z x -y pkg-config_0.26-1_win32.zip -oC:\pkg-config > nul
  - 7z x -y glib_2.28.8-1_win32.zip -oC:\pkg-config > nul
  - 7z x -y gettext-runtime_0.18.1.1-2_win32.zip -oC:\pkg-config > nul

build_script:
  # Install the dependencies of the project.
  - python -m pip install %NP_BUILD_DEP%

  # Build wheel
  - python -m pip install wheel
  - cd %PACKAGE_DIR%
#    - git checkout %BUILD_COMMIT%
#    - git apply ..\patches\free_space_in_dir.path
  - python setup.py bdist_wheel

test_script:
  # create test env
  - virtualenv --python %PYTHON%\Python.exe test_env
  - test_env\Scripts\activate.bat
  - where python
  - python -m pip install %NP_TEST_DEP%

  # install from wheel
  - python -m pip install --pre --no-index --find-links %REPO_DIR%\dist\ %PACKAGE_NAME%

  # Change into an innocuous directory and find tests from installation
  - mkdir for_testing
  - cd for_testing
  - python --version
  - python -c "import astropy; astropy.test(remote_data='none')"
  - cd ..

artifacts:
  - path: "%REPO_DIR%\\dist\\*"

on_success:
  # Upload the generated wheel package to Rackspace
  # On Windows, Apache Libcloud cannot find a standard CA cert bundle so we
  # disable the ssl checks.
  - python -m pip install wheelhouse-uploader
  - "python -m wheelhouse_uploader upload
    --no-ssl-check --local-folder=%REPO_DIR%\\dist --no-update-index wheels"