env:
  global:
    - REPO_DIR="metric"
    - PACKAGE_DIR="metric/python"
    - BUILD_COMMIT=HEAD
    - PLAT=x86_64
    - BUILD_DEPENDS="auditwheel==3.1.0"
    - TEST_DEPENDS="pytest"
    - UNICODE_WIDTH=32
    - PYPI_SERVER="https://test.pypi.org/legacy/"
    - secure: YWYvyfWo3bD4q/RCPiACRFeGLJiAskWqElaCSl6Ag/72B4jaZE4JADE3YMuwkVKM//TnWMncHYxFDjIbQ7ZrQjbom6ZEQuEHCAILbcuRDiZj+1WJWgxPNG2uB82MT6eLqcfSxpo5eAH3aC4q0qixO+Px28w1ifmBpbvEx2uHgpjB+b44UjpGTc85XHkOvbc2BFYOS2bvKzi/I6jx/vWyCHo+6tKPsHFSKYMup/fbAIs+PDZ1SvAlJwfSbqu8nt+weMkK1cds0vl9j79bO5d3pb8bVI9XcvS7RAny8mfvlw33ZT2PcLboyHRx5Xa9N/k+huZlP6UXjLF85qvp85/UjMYiksUEgzx5pcSX+qYhR/Ffr1GoCOyzv+61CpzsQXgzfntoN2O3Vl517GO67jxDw2IvOqaeyBX9hSXU++yBG96peIYlESya3XtxAUG+HWDlHg35orPsL+x85B0WUykcRsQAKWxuRBwKViUK7xu8RB4YBSoYdBlr7cUiaDqKnWp+wvhVjvKOPOGJLg9S2q98qhbWbvC6I4KxeoCAIQaGERSyv1jHcqulQsxw0YZAlZWAoLHxMojL7o6hVc/wSKxQCyTfY2Y1c5zgCTvafKP2qmqTAzu+gIaUY8rzhcO+Ig5r7cOw+elq2wO8UE95HAjAdfovwJ4/++zJj4wkynF6TKs=
    - MB_PYTHON_VERSION=3.7
language: generic
python: 3.7
dist: xenial
services: docker

jobs:
  include:
  # Linux builds
#    - os: linux
#      env:
#        - MB_PYTHON_VERSION=3.6
#    - os: linux
#      env:
#        - MB_PYTHON_VERSION=3.7
#    - os: linux
#      env:
#        - MB_PYTHON_VERSION=3.8
#   OSX builds
#    - os: osx
#      env:
#        - MB_PYTHON_VERSION=3.6
#        - VENV=venv
#    - os: osx
#      env:
#        - MB_PYTHON_VERSION=3.7
#        - VENV=venv
#    - os: osx
#      env:
#        - MB_PYTHON_VERSION=3.8
#        - VENV=venv
  # Default OSX (xcode image) is 10.13 (xcode 9.4.1) as of 2020-03-24
  # See: https://docs.travis-ci.com/user/reference/osx/
#    - os: osx
#      osx_image: xcode10.3
#      env:
#        - MB_PYTHON_VERSION=3.6
#        - VENV=venv
#        - MB_PYTHON_OSX_VER=10.9
    - os: osx
      osx_image: xcode10.3
      env:
        - MB_PYTHON_VERSION=3.7
        - VENV=venv
        - MB_PYTHON_OSX_VER=10.9
    - os: osx
      osx_image: xcode10.3
      env:
        - MB_PYTHON_VERSION=3.8
        - VENV=venv
        - MB_PYTHON_OSX_VER=10.9
#    - os: osx
#      osx_image: xcode11
#      env:
#        - MB_PYTHON_VERSION=3.6
#        - VENV=venv
#        - MB_PYTHON_OSX_VER=10.9
#    - os: osx
#      osx_image: xcode11.3
#      env:
#        - MB_PYTHON_VERSION=3.6
#        - VENV=venv
#        - MB_PYTHON_OSX_VER=10.9
#    - os: osx
#      osx_image: xcode10
#      env:
#        - MB_PYTHON_VERSION=3.6
#    - os: osx
#      osx_image: xcode11.2
#      env:
#        - MB_PYTHON_VERSION=3.7
#    - os: osx
#      osx_image: xcode10.3
#      env:
#        - MB_PYTHON_VERSION=3.6
#    - os: osx
#      env:
#        - MB_PYTHON_VERSION=3.7
#    - os: osx
#      osx_image: xcode10
#      env:
#        - MB_PYTHON_VERSION=3.8
#    - os: osx
#      osx_image: xcode11.3
#      env:
#        - MB_PYTHON_VERSION=3.6
#    - os: osx
#      osx_image: xcode11.3
#      env:
#        - MB_PYTHON_VERSION=3.7
#    - os: osx
#      osx_image: xcode11.3
#      env:
#        - MB_PYTHON_VERSION=3.8
    - os: windows
      env:
        - MB_PYTHON_VERSION=3.8

before_install:
  - source multibuild/common_utils.sh
  - source multibuild/travis_steps.sh
  - before_install
install:
  - clean_code $REPO_DIR $BUILD_COMMIT
  - build_wheel $PACKAGE_DIR $PLAT
#script:
#  - install_run $PLAT
after_success:
  - source publish.sh
  - upload_to_pypi $PYPI_SERVER
