env:
  global:
    - REPO_DIR="metric"
    - PACKAGE_DIR="metric/python"
    - BUILD_COMMIT=HEAD
    - PLAT=x86_64
    - BUILD_DEPENDS="auditwheel==3.1.0"
    - TEST_DEPENDS="pytest"
    - UNICODE_WIDTH=32
    - TWINE_REPOSITORY_URL="https://upload.pypi.org/legacy/"
    - secure: K/9THjcJ6emu7Fgfl1l9fFcPbZew3l5/8UCGP/Xn/hJJO6oSQnM6YQkJSdm4mCCOT8pAz86TVH2lH4rhXcDjq5fwrvt+RyWzFlnG0KjBjXwpzj8VqgRc/3hNUvoByP7UpAV9/jj/WC5lc+Cb7yoE+8zH06aKnysXAXozPmr39WBGDNUtjBnI369VmU8lK3DANcE2OJFHZDx1lt8qnTXj5IEpbjt73y7NyGU1ao+UYeNdjGqFLRKPnzi02tkaU8STG+taxMf3eQ8NNz0oebruO9t18hUV6GUfqXZD2PHoBm1kyUj0G/pWdoa0x9ncJCfwpfWjE5SX/VGtv/0kxh3nuHTIi1L4+sVbw/OmPHOkiAn1hl5frEyXo7sT4EaQbjP0wPl+Eq1PkUwEZgHr19+H2hGhjrPZD9VWvvXB2cMxMIB7abbIQUdYTrAfsenE9QvafAWW38ZQninFdLD7ex5vGl1vmGw+/LFUmrbPHNXG8HcbiSrnRWcj/Ay+sob8OcplhK6Q0nH5IDpuZur27MUSO4ZGnLfNwy/BgK5cErNsDojnCVY7PJbRrLwfA/5PyPVIDwSx0epyeYOcO2q2bVxZropz1c+JO1B1JakfJC8E30O5Sb8Bra9dL6IkKXrFn1dwHavn/PJSQ64KJI7T47AAhTqWdkzcdqiKJk56qHMAK1E=
    - MB_PYTHON_VERSION=3.7
language: generic
python: 3.7
dist: xenial
services: docker

jobs:
  include:
  # Linux builds
    - os: linux
      env:
        - MB_PYTHON_VERSION=3.6
    - os: linux
      env:
        - MB_PYTHON_VERSION=3.7
    - os: linux
      env:
        - MB_PYTHON_VERSION=3.8
  # OS X builds
    - os: osx
      env:
        - MB_PYTHON_VERSION=3.6
        - VENV=venv
    - os: osx
      env:
        - MB_PYTHON_VERSION=3.7
        - VENV=venv
    - os: osx
      env:
        - MB_PYTHON_VERSION=3.8
        - VENV=venv
  # Windows builds (see .appveyor.yml)

before_install:
  - source multibuild/common_utils.sh
  - source multibuild/travis_steps.sh
  - before_install
install:
  - clean_code $REPO_DIR $BUILD_COMMIT
  - build_wheel $PACKAGE_DIR $PLAT
script:
  - install_run $PLAT
after_success:
  - source publish.sh
  - upload_to_pypi $PYPI_SERVER
